// Build the chrome assets the worker serves, straight from the owner's
// lavish-axi fork — nothing fork-derived is ever committed to this repository.
//
//   node deploy/lavish-worker/build-assets.mjs [--fork <path>] [--stub]
//
// --fork   path to the lavish-axi checkout (default: the LAVISH_AXI_SRC env
//          var, then C:/Users/panto/projects/_conveyor/lavish-axi/work)
// --stub   write assets.gen.mjs from the committed stubs instead (lets
//          wrangler dev run on a machine without the fork; the review chrome
//          will be non-functional placeholder markup)
//
// The output, assets.gen.mjs, is gitignored. It exports `assets` with:
//   chromeTemplate  createChromeHtml() rendered with __LAVISH_*__ sentinels
//   sdkJs           createSdkJs() rendered with the key sentinel
//   chromeClientJs, chromeCss, design{}  copied verbatim from the fork
//
// The worker substitutes the sentinels per request (worker.mjs). If the fork
// ever renames the structures this build relies on, the checks below fail the
// build loudly instead of shipping a broken chrome.

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, 'assets.gen.mjs');
const DEFAULT_FORK = 'C:/Users/panto/projects/_conveyor/lavish-axi/work';

const args = process.argv.slice(2);
const forkIdx = args.indexOf('--fork');
const forkDir = forkIdx >= 0 ? args[forkIdx + 1]
  : (process.env.LAVISH_AXI_SRC || DEFAULT_FORK);

async function writeAssets(assets) {
  const body = `// Generated by build-assets.mjs — do not edit, do not commit.\n`
    + `export const assets = ${JSON.stringify(assets, null, 2)};\n`;
  await writeFile(OUT, body);
  console.log(`wrote ${OUT} (version ${assets.version})`);
}

if (args.includes('--stub')) {
  const { stubAssets } = await import('./stub-assets.mjs');
  await writeAssets(stubAssets);
  process.exit(0);
}

const serverModule = path.join(forkDir, 'src', 'server.js');
let createChromeHtml, createSdkJs;
try {
  ({ createChromeHtml, createSdkJs } = await import(pathToFileURL(serverModule).href));
} catch (e) {
  console.error(`could not load ${serverModule}: ${e.message}`);
  console.error('point --fork (or LAVISH_AXI_SRC) at a lavish-axi checkout with node_modules installed,');
  console.error('or run with --stub for placeholder assets.');
  process.exit(1);
}
if (typeof createChromeHtml !== 'function' || typeof createSdkJs !== 'function') {
  console.error(`the fork at ${forkDir} no longer exports createChromeHtml/createSdkJs — update this build script.`);
  process.exit(1);
}

const version = JSON.parse(await readFile(path.join(forkDir, 'package.json'), 'utf8')).version;

const chromeTemplate = createChromeHtml(
  {
    key: '__LAVISH_KEY__',
    file: '__LAVISH_FILE__',
    status: 'open',
    ended_by: null,
    chat: [],
    layout_warnings: [],
  },
  {
    layoutGateEnabled: false,
    title: '__LAVISH_TITLE__',
    artifactRevision: 0,
    artifactLoadToken: '',
    artifactLoadSequence: 0,
    chromeLoadToken: '',
  },
);
const sdkJs = createSdkJs('__LAVISH_KEY__', 0, '');

// The worker's substitutions depend on these structures — fail here, not there.
const checks = [
  [/<script id="lavish-session" type="application\/json">[\s\S]*?<\/script>/.test(chromeTemplate),
    'chrome template: lavish-session JSON block'],
  [chromeTemplate.includes('data-artifact-src="/artifact/__LAVISH_KEY__/index.html"'),
    'chrome template: artifact iframe src'],
  [chromeTemplate.includes('__LAVISH_TITLE__'), 'chrome template: title sentinel'],
  [/const key="__LAVISH_KEY__";/.test(sdkJs), 'sdk.js: key declaration'],
  [/const artifactRevision=\d+;/.test(sdkJs), 'sdk.js: revision declaration'],
  [/const artifactLoadToken="";/.test(sdkJs), 'sdk.js: load token declaration'],
];
const failed = checks.filter(([ok]) => !ok).map(([, name]) => name);
if (failed.length) {
  console.error(`the fork's output no longer matches what the worker rewrites:\n  ${failed.join('\n  ')}`);
  console.error('update worker.mjs and this build script together.');
  process.exit(1);
}

const src = (...p) => path.join(forkDir, 'src', ...p);
const design = {};
for (const name of ['daisyui.css', 'daisyui-themes.css', 'tailwindcss-browser.js']) {
  // Packaged copies live in src/design; fall back to the packages themselves.
  const candidates = [
    src('design', name),
    path.join(forkDir, 'node_modules', 'daisyui', name),
    path.join(forkDir, 'node_modules', '@tailwindcss', 'browser', 'dist', 'index.global.js'),
  ];
  let content = null;
  for (const candidate of candidates) {
    try { content = await readFile(candidate, 'utf8'); break; } catch { /* next */ }
  }
  if (content === null) {
    console.error(`could not find design asset ${name} under ${forkDir}`);
    process.exit(1);
  }
  design[name] = content;
}

await writeAssets({
  version,
  chromeTemplate,
  chromeClientJs: await readFile(src('chrome-client.js'), 'utf8'),
  chromeCss: await readFile(src('chrome.css'), 'utf8'),
  sdkJs,
  design,
});
